name: ontoprobe_dbt
version: "0.1.0"
config-version: 2

profile: ontoprobe

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]
